/**
 * Centralized API Routes map following API Contract V1
 */

export const API_ROUTES = {
  AUTH: {
    LOGIN: "/api/auth/login",
    LOGOUT: "/api/auth/logout",
  },
  PROFILE: {
    GET: "/api/auth/me",
    UPDATE: "/api/auth/me",
  },
  DASHBOARD: {
    SUMMARY: "/api/dashboard/summary",
    ADMIN: "/api/dashboard/admin",
    TEACHER: "/api/dashboard/teacher",
    STUDENT: "/api/dashboard/student",
  },
  ATTENDANCE: {
    SESSIONS: "/api/attendance/sessions",
    SESSION_DETAIL: (id) => `/api/attendance/sessions/${id}`,
    CLOSE_SESSION: (id) => `/api/attendance/sessions/${id}/close`,
    RECORDS: (id) => `/api/attendance/sessions/${id}/records`,
    BULK: (id) => `/api/attendance/sessions/${id}/bulk`,
    MY: "/api/attendance/my",
  },
  MATERIALS: {
    LIST: "/api/materials",
    MY: "/api/materials/my",
    DETAIL: (id) => `/api/materials/${id}`,
  },
  ASSIGNMENTS: {
    LIST: "/api/assignments",
    MY: "/api/assignments/my",
    DETAIL: (id) => `/api/assignments/${id}`,
    SUBMISSIONS: (id) => `/api/assignments/${id}/submissions`,
  },
  SUBMISSIONS: {
    SUBMIT: "/api/submissions",
    DETAIL: (id) => `/api/submissions/${id}`,
    GRADE: (id) => `/api/submissions/${id}/grade`,
    MY_SUBMISSION: (assignmentId) => `/api/submissions/assignment/${assignmentId}/my`,
  },
  ANNOUNCEMENTS: {
    LIST: "/api/announcements",
    SHOWCASE: "/api/announcements/showcase",
    DETAIL: (id) => `/api/announcements/${id}`,
    TOGGLE_SHOWCASE: (id) => `/api/announcements/${id}/showcase`,
    REACTIONS: (id) => `/api/announcements/${id}/reactions`,
    COMMENTS: (id) => `/api/announcements/${id}/comments`,
  },
  ANNOUNCEMENT_COMMENTS: {
    BY_ANNOUNCEMENT: (id) => `/api/announcements/${id}/comments`,
    DELETE: (announcementId, commentId) => `/api/announcements/${announcementId}/comments/${commentId}`,
    TOGGLE_LOCK: (announcementId) => `/api/announcements/${announcementId}/comments/toggle-lock`,
  },
  SHOWCASE_BANNERS: {
    LIST: "/api/showcase-banners",
    ALL: "/api/showcase-banners/all",
    DETAIL: (id) => `/api/showcase-banners/${id}`,
    CREATE: "/api/showcase-banners",
    FROM_ANNOUNCEMENT: (announcementId) => `/api/showcase-banners/from-announcement/${announcementId}`,
    UPDATE: (id) => `/api/showcase-banners/${id}`,
    DELETE: (id) => `/api/showcase-banners/${id}`,
    RESTORE: (id) => `/api/showcase-banners/${id}/restore`,
    REORDER: "/api/showcase-banners/reorder",
  },
  BOOKINGS: {
    LIST: "/api/bookings",
    CREATE: "/api/bookings",
  },
  EXTRACURRICULARS: {
    LIST: "/api/extracurriculars",
    DETAIL: (id) => `/api/extracurriculars/${id}`,
    JOIN: (id) => `/api/extracurriculars/${id}/join`,
    LEAVE: (id) => `/api/extracurriculars/${id}/leave`,
    MEMBERS: (id) => `/api/extracurriculars/${id}/members`,
    SUPERVISED: "/api/extracurriculars/supervised",
  },
  PROPOSALS: {
    LIST: "/api/proposals",
    DETAIL: (id) => `/api/proposals/${id}`,
    REVIEW: (id) => `/api/proposals/${id}/review`,
  },
  FACILITIES: {
    LIST: "/api/facilities",
    DETAIL: (id) => `/api/facilities/${id}`,
    SLOTS: (id) => `/api/facilities/${id}/slots`,
  },
  CALENDAR: {
    LIST: "/api/calendar",
    MONTH: "/api/calendar/month",
    DAY: "/api/calendar/day",
    UPCOMING: "/api/calendar/upcoming",
    DETAIL: (id) => `/api/calendar/${id}`,
  },
  USERS: {
    LIST: "/api/users",
    DETAIL: (id) => `/api/users/${id}`,
    TEACHERS: "/api/users/teachers",
    IMPORT_STUDENTS: "/api/users/import-students",
    IMPORT_TEACHERS: "/api/users/import-teachers",
    EXPORT_STUDENTS: "/api/users/export-students",
    ASSIGN_TEACHER: "/api/users/assign-teacher",
  },
  DEPARTMENTS: {
    LIST: "/api/departments",
    DETAIL: (id) => `/api/departments/${id}`,
  },
  CLASSES: {
    LIST: "/api/classes",
    DETAIL: (id) => `/api/classes/${id}`,
  },
  ACADEMIC_YEARS: {
    LIST: "/api/academic-years",
    DETAIL: (id) => `/api/academic-years/${id}`,
    SET_ACTIVE: (id) => `/api/academic-years/${id}/set-active`,
  },
  SEMESTERS: {
    LIST: "/api/semesters",
    DETAIL: (id) => `/api/semesters/${id}`,
    SET_ACTIVE: (id) => `/api/semesters/${id}/set-active`,
  },
  SUBJECTS: {
    LIST: "/api/subjects",
    DETAIL: (id) => `/api/subjects/${id}`,
  },
  TEACHER_SUBJECTS: {
    LIST: "/api/teacher-subjects",
    DETAIL: (id) => `/api/teacher-subjects/${id}`,
  },
  CLASS_SUBJECTS: {
    LIST: "/api/class-subjects",
    DETAIL: (id) => `/api/class-subjects/${id}`,
  },
  SCHEDULES: {
    LIST: "/api/schedules",
    DETAIL: (id) => `/api/schedules/${id}`,
    STUDENT_TODAY: "/api/schedules/student/today",
    TEACHER_TODAY: "/api/schedules/teacher/today",
  },
  ACADEMIC_EVENTS: {
    LIST: "/api/academic-events",
    UPCOMING: "/api/academic-events/upcoming",
    DETAIL: (id) => `/api/academic-events/${id}`,
  },
  NOTIFICATIONS: {
    LIST: "/api/notifications",
    SUMMARY: "/api/notifications/summary",
    UNREAD_COUNT: "/api/notifications/unread-count",
    MARK_READ: (id) => `/api/notifications/${id}/read`,
    MARK_ALL_READ: "/api/notifications/read-all",
    DELETE: (id) => `/api/notifications/${id}`,
    BROADCAST: "/api/notifications/broadcast",
  },
  GRADE_CATEGORIES: {
    LIST: "/api/grade-categories",
    DETAIL: (id) => `/api/grade-categories/${id}`,
  },
  ASSESSMENTS: {
    LIST: "/api/assessments",
    DETAIL: (id) => `/api/assessments/${id}`,
    PUBLISH: (id) => `/api/assessments/${id}/publish`,
  },
  STUDENT_GRADES: {
    GRADEBOOK: (classSubjectId) => `/api/student-grades/gradebook/${classSubjectId}`,
    MY: "/api/student-grades/my",
    TRANSCRIPT: "/api/student-grades/transcript",
    REPORT_CARD: "/api/student-grades/report-card",
    BULK: "/api/student-grades/bulk",
    PUBLISH: (assessmentId) => `/api/student-grades/publish/${assessmentId}`,
    IMPORT_CSV: "/api/student-grades/import-csv",
    EXPORT_CSV: (assessmentId) => `/api/student-grades/export-csv/${assessmentId}`,
  },
  GRADE_SCALES: {
    LIST: "/api/grade-scales",
    DETAIL: (id) => `/api/grade-scales/${id}`,
  },
  DISCUSSIONS: {
    LIST: "/api/discussions",
    DETAIL: (id) => `/api/discussions/${id}`,
    BY_CLASS_SUBJECT: (classSubjectId) => `/api/discussions/class-subject/${classSubjectId}`,
    REPLIES: (threadId) => `/api/discussions/replies/thread/${threadId}`,
    CREATE_REPLY: "/api/discussions/replies",
    DELETE_REPLY: (id) => `/api/discussions/replies/${id}`,
    PIN: (id) => `/api/discussions/${id}/pin`,
    LOCK: (id) => `/api/discussions/${id}/lock`,
  },
  CONVERSATIONS: {
    LIST: "/api/conversations",
    CREATE: "/api/conversations",
    DETAIL: (id) => `/api/conversations/${id}`,
    MARK_READ: (id) => `/api/conversations/${id}/read`,
    UNREAD_COUNT: "/api/conversations/unread-count",
  },
  MESSAGES: {
    SEND: "/api/messages",
    BY_CONVERSATION: (conversationId) => `/api/messages/conversation/${conversationId}`,
    DELETE: (id) => `/api/messages/${id}`,
  },
  ANNOUNCEMENT_COMMENTS: {
    BY_ANNOUNCEMENT: (annId) => `/api/announcements/${annId}/comments`,
    DELETE: (annId, commentId) => `/api/announcements/${annId}/comments/${commentId}`,
    TOGGLE_LOCK: (annId) => `/api/announcements/${annId}/comments/toggle-lock`,
  },
  CALENDAR: {
    LIST: "/api/calendar",
    UPCOMING: "/api/calendar/upcoming",
    DETAIL: (id) => `/api/calendar/${id}`,
  },
  ADMIN_EMAIL: {
    CONFIG: "/api/admin/email/config",
    TEST: "/api/admin/email/test",
    LOGS: "/api/admin/email/logs",
    LOG_DETAIL: (id) => `/api/admin/email/logs/${id}`,
  },
  NOTIFICATION_EMAIL: {
    REQUEST_OTP: "/api/users/notification-email/request-otp",
    VERIFY_OTP: "/api/users/notification-email/verify-otp",
    DELETE: "/api/users/notification-email",
  },
  FEEDBACK: {
    CREATE: "/api/feedback",
    LIST: "/api/feedback",
    SUMMARY: "/api/feedback/summary",
    UPDATE_STATUS: (id) => `/api/feedback/${id}/status`,
    DELETE: (id) => `/api/feedback/${id}`,
  },
};
