<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\backend\StudentCenter.Domain\StudentCenter.Domain.csproj" />
    <ProjectReference Include="..\..\backend\StudentCenter.Application\StudentCenter.Application.csproj" />
    <ProjectReference Include="..\..\backend\StudentCenter.Infrastructure\StudentCenter.Infrastructure.csproj" />
  </ItemGroup>
</Project>
