import { executeAiTool } from "@/services/aiTools";

/**
 * Official AI Action Dispatcher for Replyz Assistant
 * Connects JSON actions generated by Groq LLM / Gemini API to React Router, DOM Spotlighting, Modals, and Backend API fetchers.
 */
export async function dispatchAiAction(actionPayload, context = {}) {
  if (!actionPayload || typeof actionPayload !== "object") {
    return { success: false, message: "Action payload tidak valid." };
  }

  const { action, params = {} } = actionPayload;
  const { router } = context;

  if (!action) {
    return { success: true, message: "Tidak ada aksi UI yang dieksekusi." };
  }

  switch (action) {
    case "navigate": {
      const route = params.route || "/";
      return await executeAiTool("navigate_to_page", { route }, { router });
    }

    case "open_modal": {
      const modalName = params.modalName === "notifications" ? "notification_center" : params.modalName || "login";
      return await executeAiTool("open_modal", { modalName }, context);
    }

    case "highlight_ui": {
      const target = params.target || "login_button";
      return await executeAiTool("highlight_ui_element", { target }, context);
    }

    case "fetch_data": {
      const endpoint = params.endpoint || "";
      if (endpoint.includes("announcement") || endpoint.includes("mading")) {
        return await executeAiTool("get_latest_announcements", params, context);
      }
      if (endpoint.includes("schedule") || endpoint.includes("jadwal")) {
        return await executeAiTool("get_class_schedule", params, context);
      }
      if (endpoint.includes("notif")) {
        return await executeAiTool("get_user_notifications", params, context);
      }
      return await executeAiTool("get_latest_announcements", params, context);
    }

    default:
      console.warn(`[AI Action Dispatcher] Unrecognized action '${action}'`);
      return { success: false, message: `Aksi '${action}' tidak dikenali.` };
  }
}

export default dispatchAiAction;
